version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 9.0
  build:
    commands:
      - echo "Restoring packages..."
      - dotnet restore
      - echo "Building app..."
      - dotnet publish -c Release -o published-app
artifacts:
  files:
    - '**/*'
  base-directory: published-app
