version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - echo "Restoring packages..."
      - dotnet restore
      - echo "Building app..."
      - dotnet publish -c Release -o published-app
      - echo "web: dotnet Nkolex.Propman.Server.dll" > published-app/Procfile 
artifacts:
  base-directory: published-app
  files:
    - '**/*'