name: CI/CD - Deploy .NET API to DigitalOcean

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run xUnit Tests
        run: |
          echo "Running xUnit tests..."
          dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Copy files to Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          source: "./publish/*"
          target: "/var/www/html/backend/propmanserver"
          
      - name: Set correct ownership & permissions
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          script: |
            echo "Fixing ownership and permissions..."
            # Ensure the deployment folder is owned by root
            chown -R root:root /var/www/html/backend/propmanserver
            # Ensure Data folder is writable
            chmod -R 755 /var/www/html/backend/propmanserver/publish/Data

      - name: Restart API service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          script: |
              echo "Connected to $(hostname)"
              whoami
              ls -la /etc/systemd/system | grep propmanserver
              echo "Restarting service..."
              systemctl restart propmanserver || echo "Restart failed with code $?"
              systemctl status propmanserver --no-pager